export const ADD_INGREDIENT_INTO_CONSTRUCTOR =
  'ADD_INGREDIENT_INTO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR =
  'REMOVES_INGREDIENT_FROM_CONSTRUCTOR';
export const MOVE_INGREDIENT_IN_CONSTRUCTOR = 'MOVE_INGREDIENT_IN_CONSTRUCTOR';
export const EMPTY_CONSTRUCTOR = 'EMPTY_CONSTRUCTOR';
